### ISSUE TITLE
Generators in a comunica standalone project

### ISSUE THREAD

**Issue by SvenLieber** [comunica/generate-comunica#4]
According to the [documentation](https://comunica.readthedocs.io/en/latest/tutorials/feature-comunica/#implement-a-feature-into-a-standalone-project), the yeoman generators can be used in a standalone project like in the monorepo (assuming that needed dependencies are installed).

I have `"@comunica/core": "^1.0.0"` as dev dependency installed, but `yo comunica:actor` throws the error

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '/home/slieber/repos/comunica-shapes-processor/./packages/core/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at module.exports.writing (/home/slieber/repos/generate-comunica/generators/actor/index.js:119:41)
    at Object.<anonymous> (/home/slieber/repos/generate-comunica/node_modules/yeoman-generator/lib/index.js:399:25)
    at /home/slieber/repos/generate-comunica/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/slieber/repos/generate-comunica/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/slieber/repos/generate-comunica/node_modules/yeoman-generator/lib/index.js:400:11)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/slieber/repos/generate-comunica/node_modules/yeoman-generator/lib/index.js:406:18)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)

```

Instead of looking into `./node_modules/@comunica/core` directory, the generator assumes the comunica core to be present in the current directory.

**Comment by rubensworks** [comment]
Note to self: we should autodetect the presence of a monorepo. If it is not present, it should look for `@comunica/core` in `node_modules/`.

**Comment by rubensworks** [comment]
Done in 84e19c6b54573db1c091e44769565255b1abbe38
